# Generated by Django 5.1.2 on 2024-11-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_completed',
            field=models.BooleanField(default=False),
        ),
    ]
