# Generated by Django 5.1.2 on 2024-11-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_booking_service_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
