# Generated by Django 5.1.2 on 2024-10-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.FloatField(default=121.4),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.FloatField(default=131.5),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='latitude',
            field=models.FloatField(default=121.4),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='longitude',
            field=models.FloatField(default=131.5),
        ),
    ]
