# Generated by Django 5.1.2 on 2024-10-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_customer_latitude_alter_customer_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='location',
        ),
    ]
